name: 'Staging Docker Registry Push'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Login to GitHub Container Registry'
        uses: 'docker/login-action@v3'
        with:
          registry: ghcr.io
          username: 'rylero'
          password: "${{ secrets.CR_PAT }}"
          
      - name: 'Build and Push Container'
        working-directory: ./backend
        run: |-
          DOCKER_TAG="ghcr.io/rylero/politiscan:latest"
          docker buildx build --tag "${DOCKER_TAG}" --build-arg GROK_API="${{ secrets.GROK_API }}" --build-arg BRAVE_API="${{ secrets.BRAVE_API }}" .
          docker push "${DOCKER_TAG}"

